apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: ReplicationController
metadata:
  labels:
    name: client
  name: client-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
      - image: gcr.io/tactical-unison-138523/client
        name: client
        ports:
        - containerPort: 8000
          name: client
